### ISSUE TITLE
Выходит боковое поле справа

### ISSUE THREAD

**Issue by NursultanMuss** [agragregra/wordpress-landing-page-lesson#4]
Здравствуйте. Я сделал по вашему уроку внешний вид сайта, но есть проблема выходит справа поле серое при скролле вниз. И я пока не могу от него избавиться. Прошу помочь с решением проблемы!

**Comment by MAXON-BY** [comment]
Приветствую! А где код? ССылка на сайт? Как должны по вашему сообщению ВАМ помочь?

**Comment by NursultanMuss** [comment]
https://github.com/NursultanMuss/clean.git

> Приветствую! А где код? ССылка на сайт? Как должны по вашему сообщению ВАМ помочь?

https://github.com/NursultanMuss/clean.git - ссылка на репозиторий
